jobs: [
  ##################################################################################################
  #  Flips
  ##################################################################################################
  # Kitchen/panda - 180 rotation.
  # ------------------------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/kitchen_panda/va_reproduction,
    context_list: [
      {prompt: a painting of kitchenware},
      {prompt: a painting of a red panda}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False},
    # seed: 0
  },
  {
    trial_name: sumaiya_output/kitchen_panda/mcmc,
    context_list: [
      {prompt: a painting of kitchenware},
      {prompt: a painting of a red panda}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True},
  },
  # Unconditional
  # - Ablation
  # ---------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/kitchen_panda/va_unconditional,
    context_list: [
      {prompt: a painting of kitchenware},
      {prompt: a painting of a red panda}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False, unconditional: True},
    # seed: 0
  },
  {
    trial_name: sumaiya_output/kitchen_panda/mcmc_unconditional,
    context_list: [
      {prompt: a painting of kitchenware},
      {prompt: a painting of a red panda}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True, unconditional: True},
    # seed: 0
  },



  # Dog/flower jobs - 180 rotation.
  # ------------------------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/dog_flower/va_reproduction,
    context_list: [
      {prompt: a painting of a dog},
      {prompt: a painting of a flower}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False}
  },
  {
    trial_name: sumaiya_output/dog_flower/mcmc,
    context_list: [
      {prompt: a painting of a dog},
      {prompt: a painting of a flower}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True}
  },

  # Unconditional
  # - Ablation
  # ---------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/dog_flower/va_unconditional,
    context_list: [
      {prompt: a painting of a dog},
      {prompt: a painting of a flower}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False, unconditional: True}
  },
  {
    trial_name: sumaiya_output/dog_flower/mcmc_unconditional,
    context_list: [
      {prompt: a painting of a dog},
      {prompt: a painting of a flower}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True, unconditional: True}
  },



  # Fish/duck - 180 rotation.
  # ------------------------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/fish_duck/va_reproduction,
    context_list: [
      {prompt: a lithograph of a fish},
      {prompt: a lithograph of a duck}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False}
  },
  {
    trial_name: sumaiya_output/fish_duck/mcmc,
    context_list: [
      {prompt: a lithograph of a fish},
      {prompt: a lithograph of a duck}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True}
  },

  # Unconditional
  # - Ablation
  # ---------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/fish_duck/va_unconditional,
    context_list: [
      {prompt: a lithograph of a fish},
      {prompt: a lithograph of a duck}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False, unconditional: True}
  },
  {
    trial_name: sumaiya_output/fish_duck/mcmc_unconditional,
    context_list: [
      {prompt: a lithograph of a fish},
      {prompt: a lithograph of a duck}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True, unconditional: True}
  },



  # Penguin/giraffe - 180 rotation.
  # ------------------------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/penguin_giraffe/va_reproduction,
    context_list: [
      {prompt: a drawing of a giraffe},
      {prompt: a drawing of a penguin}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False}
  },
  {
    trial_name: sumaiya_output/penguin_giraffe/mcmc,
    context_list: [
      {prompt: a drawing of a giraffe},
      {prompt: a drawing of a penguin}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True}
  },

  # Unconditional
  # - Ablation
  # ---------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/penguin_giraffe/va_unconditional,
    context_list: [
      {prompt: a drawing of a giraffe},
      {prompt: a drawing of a penguin}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False, unconditional: True}
  },
  {
    trial_name: sumaiya_output/penguin_giraffe/mcmc_unconditional,
    context_list: [
      {prompt: a drawing of a giraffe},
      {prompt: a drawing of a penguin}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True, unconditional: True}
  },



  # Young/old woman - 180 rotation.
  # ------------------------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/young_old_woman/va_reproduction,
    context_list: [
      {prompt: a photo of a young lady},
      {prompt: a photo of an old woman}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False}
  },
  {
    trial_name: sumaiya_output/young_old_woman/mcmc,
    context_list: [
      {prompt: a photo of a young lady},
      {prompt: a photo of an old woman}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True}
  },

  # Unconditional
  # - Ablation
  # ---------------------------------------------------------------------------------
  {
    trial_name: sumaiya_output/young_old_woman/va_unconditional,
    context_list: [
      {prompt: a photo of a young lady},
      {prompt: a photo of an old woman}
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False, unconditional: True}
  },
  {
    trial_name: sumaiya_output/young_old_woman/mcmc_unconditional,
    context_list: [
      {prompt: a photo of a young lady},
      {prompt: a photo of an old woman}
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True, unconditional: True}
  },







  ##################################################################################################
  # Independent Synthesis/Guidance Magnitude
  ##################################################################################################


  ##################################################################################################
  # Drastically Different Prompts
  # - Idea is to check if MCMC can handle the independent synthesis, or capturing both classes
  #   better in the images than pure VA can. Doubt it
  ##################################################################################################
  {
    trial_name: sumaiya_output/drastically_different_prompts/old_woman_photo_jackson_pollock/va_reproduction,
    context_list: [
      {prompt: a photo of an old woman},
      {
        prompt: a painting by Jackson Pollock,
        view: "flip"
      }
    ],
    stage_1_args: {using_mcmc_sampling: False},
    stage_2_args: {using_mcmc_sampling: False}
  },
  {
    trial_name: sumaiya_output/drastically_different_prompts/old_woman_photo_jackson_pollock/mcmc,
    context_list: [
      {prompt: a photo of an old woman},
      {
        prompt: a painting by Jackson Pollock,
        view: "flip"
      }
    ],
    stage_1_args: {using_mcmc_sampling: True},
    stage_2_args: {using_mcmc_sampling: True}
  },

  ##################################################################################################
  # Correlated Noise Experiments
  # - This requires some views that had some cryptic dependency issues
  ##################################################################################################
  # {
  #   trial_name: sumaiya_output/corr_noise/
  # }

  ##################################################################################################
  # Noise Shift Experiments
  # - This requires some views that had some cryptic dependency issues
  ##################################################################################################
  # {
  #   trial_name: sumaiya_output/noise_shift/
  # }
]